version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=a1a1a1
      - DB_NAME=mydatabase
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: a1a1a1
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
